id: P57C20D47
initial_creation_type: ocr
source_metadata:
  volumes:
    11652fa80e2c46a4b05aecb7d048a765:
      base_file: v024.txt
      image_group_id: I1PD95869
      title: ལས་ཀྱི་རྡོ་རྗེ་གཽ་རཱིའི་སྒྲུབ་ཐབས།
      total_pages: 1586
      volume_number: 24
